import "./styles.css";

type EquipmentState = "recommended" | "approved" | "printed" | "archived";
export type LanguageCode = "zh" | "en";

export interface EquipmentRecommendation {
  id?: number;
  analysisDate?: string;
  equipmentName: string;
  equipmentType: string;
  whyThisEquipment: string;
  sourceBattleInsight: string;
  minimumViableVersion: string;
  expectedBenefit: string;
  printPrompt: string;
  state: EquipmentState;
}

export interface DailyBattleAnalysis {
  analysisDate: string;
  thoughtTitle: string;
  thoughtSummary?: string;
  coreThemes: string[];
  repeatedQuestions: string[];
  newlyFormedJudgments: string[];
  unclosedThinkingLoops: string[];
  reusableMaterial: string[];
  threadsToContinueTomorrow: string[];
  recommendedEquipment: EquipmentRecommendation[] | EquipmentRecommendation;
}

interface AnalyzeResponse {
  analysis?: DailyBattleAnalysis;
  mode?: "preview" | "manual-preview";
}

interface EquipmentListResponse {
  items: EquipmentRecommendation[];
}

interface ManualPromptResponse {
  date: string;
  prompt: string;
}

interface StatusResponse {
  dataRoot: string;
  capturedMessages: number;
}

export interface RuntimeConfig {
  baseUrl: string;
  model: string;
  hasApiKey: boolean;
  extensionOrigins: string;
  protocol: string;
}

type ConsoleMode = "collection" | "preview";

const serviceUrl = "http://127.0.0.1:3987";
export const REFRESH_INTERVAL_MS = 10000;
const LANGUAGE_STORAGE_KEY = "age-fx-console-language";

const translations = {
  zh: {
    language: "语言",
    chinese: "中文",
    english: "English",
    dailyBattleAnalysis: "今日战况分析",
    recommendedEquipment: "推荐装备",
    noCapturedEntries: "这条分析通道还没有捕获内容。",
    noEquipment: "尚未生成装备",
    formalEquipment: "正式装备会在午夜结算后生成。",
    data: "数据",
    capture: "捕获",
    cFunnelsCapture: "C-Funnels 捕获",
    online: "在线",
    capturedMessage: "1 条捕获消息",
    capturedMessages: "{count} 条捕获消息",
    fxBurst: "FX 爆发",
    enterFxBurst: "进入爆发",
    exitFxBurst: "退出爆发",
    fxBurstActive: "FX BURST MODE: ACTIVE",
    equipmentPrintChamber: "装备打印舱",
    printChamberCopy: "聚焦今日推荐装备。确认后进入打印队列；暂存则归档等待以后处理。",
    confirmPrint: "确认打印",
    archiveEquipment: "暂存档案",
    sourceBattleInsight: "来源洞察",
    equipmentType: "装备类型",
    noPrintableEquipment: "尚无可打印装备",
    noPrintableEquipmentCopy: "等待午夜正式结算，或先启动今日临时预览来检查捕获质量。",
    equipmentStateUpdated: "装备状态已更新",
    equipmentStateFailed: "装备状态更新失败",
    navBattle: "战况",
    navEquipment: "装备",
    navApi: "API",
    navManualBridge: "手动桥",
    minimumVersion: "最小版本",
    expectedBenefit: "预期收益",
    printPrompt: "打印提示词",
    analysisFaultEyebrow: "分析通道故障",
    analysisFaultTitle: "AGE-FX 分析通道中断",
    apiSettings: "API 设置",
    apiSettingsCopy: "修改外部模型 API。保存后，后续预览和午夜结算会使用新配置。",
    baseUrl: "Base URL",
    model: "模型",
    protocol: "协议",
    responsesApi: "OpenAI Responses API",
    chatCompletionsCompatible: "Chat Completions 兼容",
    apiKey: "API Key",
    apiKeyConfigured: "API Key 已配置",
    apiKeyMissing: "API Key 未配置",
    apiKeyPlaceholder: "留空则保留当前 key；输入新 key 则替换",
    extensionOrigins: "扩展来源",
    saveApiSettings: "保存 API 设置",
    settingsSaved: "配置已保存",
    formalSettlementNote: "{date} 正式结算。装备来自午夜刚刚结束的完整一天。",
    manualPreviewNote:
      "{date} 手动模型桥预览。这不会存储分析，也不会创建正式装备。",
    temporaryPreviewNote:
      "{date} 今日临时全量扫描。这不会存储分析，也不会创建正式装备。",
    livePreview: "测试预览",
    livePreviewCopy:
      "这是当天已捕获内容的临时扫描，不会进入正式档案，也不会创建装备。",
    manualBridgePreview: "手动模型桥预览",
    manualBridgePreviewCopy: "这份分析来自你粘贴的外部模型结果，尚未存档。",
    back: "返回",
    collectingTitle: "正在收集今日战况",
    collectionNote:
      "今天 {today} 仍在收集。{settledDate} 的正式结算会在本地午夜后出现。",
    waitingForSettlement: "等待结算",
    noFormalAnalysis: "还没有存储 {date} 的正式分析。",
    previewToday: "预览今日",
    previewTodayCopy:
      "打开今日累计捕获内容的临时扫描。它不会进入档案，也不会创建装备。",
    openPreview: "打开预览",
    previewStarting: "预览启动中，正在请求模型分析...",
    manualModelBridge: "手动模型桥",
    manualModelBridgeCopy:
      "API 额度不可用时，复制今日 AGE-FX 提示词到 ChatGPT Plus、Gemini 或其他模型，再把 JSON 结果粘贴回来作为非持久预览。",
    manualSettlementBridge: "手动结算桥",
    manualSettlementBridgeCopy:
      "如果午夜 API 结算失败，复制刚结束日期的提示词到外部模型，并把校验后的 JSON 保存为正式结算。",
    copyPrompt: "复制提示词",
    readyForDate: "{date} 就绪",
    generatedPromptLabel: "生成的手动提示词",
    pastedJsonLabel: "粘贴的手动分析 JSON",
    pasteJsonPlaceholder: "在这里粘贴 AGE-FX JSON",
    renderManualPreview: "渲染手动预览",
    saveFormalSettlement: "保存为正式结算",
    promptCopied: "提示词已复制到剪贴板。",
    promptGeneratedClipboardBlocked: "提示词已生成在下方。剪贴板权限被阻止。",
    promptGenerated: "提示词已生成在下方。",
    pasteModelJsonFirst: "请先粘贴模型 JSON。"
  },
  en: {
    language: "Language",
    chinese: "中文",
    english: "English",
    dailyBattleAnalysis: "Daily Battle Analysis",
    recommendedEquipment: "Recommended Equipment",
    noCapturedEntries: "No captured entries for this lane.",
    noEquipment: "No equipment generated",
    formalEquipment: "Formal equipment is generated by the midnight settlement.",
    data: "Data",
    capture: "Capture",
    cFunnelsCapture: "C-Funnels Capture",
    online: "Online",
    capturedMessage: "1 captured message",
    capturedMessages: "{count} captured messages",
    fxBurst: "FX Burst",
    enterFxBurst: "Enter Burst",
    exitFxBurst: "Exit Burst",
    fxBurstActive: "FX BURST MODE: ACTIVE",
    equipmentPrintChamber: "Equipment Print Chamber",
    printChamberCopy:
      "Focus the recommended equipment. Confirm to move it into the print queue, or archive it for later.",
    confirmPrint: "Confirm Print",
    archiveEquipment: "Archive",
    sourceBattleInsight: "Source Battle Insight",
    equipmentType: "Equipment Type",
    noPrintableEquipment: "No Printable Equipment",
    noPrintableEquipmentCopy:
      "Wait for the midnight settlement, or run today's temporary preview to inspect capture quality.",
    equipmentStateUpdated: "Equipment state updated",
    equipmentStateFailed: "Equipment state update failed",
    navBattle: "Battle",
    navEquipment: "Equipment",
    navApi: "API",
    navManualBridge: "Manual Bridge",
    minimumVersion: "Minimum Version",
    expectedBenefit: "Expected Benefit",
    printPrompt: "Print Prompt",
    analysisFaultEyebrow: "Analysis Channel Fault",
    analysisFaultTitle: "AGE-FX analysis channel interrupted",
    apiSettings: "API Settings",
    apiSettingsCopy:
      "Edit the external model API. Future previews and midnight settlements use the saved config.",
    baseUrl: "Base URL",
    model: "Model",
    protocol: "Protocol",
    responsesApi: "OpenAI Responses API",
    chatCompletionsCompatible: "Chat Completions Compatible",
    apiKey: "API Key",
    apiKeyConfigured: "API Key configured",
    apiKeyMissing: "API Key missing",
    apiKeyPlaceholder:
      "Leave blank to keep the current key; enter a new key to replace it",
    extensionOrigins: "Extension Origins",
    saveApiSettings: "Save API Settings",
    settingsSaved: "Config saved",
    formalSettlementNote:
      "{date} formal settlement. Equipment comes from the full day that ended at midnight.",
    manualPreviewNote:
      "{date} manual model bridge preview. This does not store analysis or create formal equipment.",
    temporaryPreviewNote:
      "{date} temporary full current-day scan. This does not store analysis or create formal equipment.",
    livePreview: "Live Preview",
    livePreviewCopy:
      "This temporary full current-day scan refreshes from all captured messages for the day. It will not enter the formal archive.",
    manualBridgePreview: "Manual Bridge Preview",
    manualBridgePreviewCopy:
      "This analysis came from a pasted external model result and has not been stored.",
    back: "Back",
    collectingTitle: "Collecting Today's Battle Record",
    collectionNote:
      "Today {today} is still collecting. Formal settlement for {settledDate} appears after local midnight.",
    waitingForSettlement: "Waiting For Settlement",
    noFormalAnalysis: "No formal analysis has been stored for {date} yet.",
    previewToday: "Preview Today",
    previewTodayCopy:
      "Open a temporary scan of today's accumulated capture. It will not enter the archive or create equipment.",
    openPreview: "Open Preview",
    previewStarting: "Preview starting. Requesting model analysis...",
    manualModelBridge: "Manual Model Bridge",
    manualModelBridgeCopy:
      "API quota unavailable? Copy today's AGE-FX prompt into ChatGPT Plus, Gemini, or another model, then paste the JSON result back as a non-persistent preview.",
    manualSettlementBridge: "Manual Settlement Bridge",
    manualSettlementBridgeCopy:
      "If midnight API settlement could not run, copy the just-ended day's prompt into an external model and save the validated JSON as the formal settlement.",
    copyPrompt: "Copy Prompt",
    readyForDate: "Ready for {date}",
    generatedPromptLabel: "Generated manual prompt",
    pastedJsonLabel: "Pasted manual analysis JSON",
    pasteJsonPlaceholder: "Paste AGE-FX JSON here",
    renderManualPreview: "Render Manual Preview",
    saveFormalSettlement: "Save As Formal Settlement",
    promptCopied: "Prompt copied to clipboard.",
    promptGeneratedClipboardBlocked:
      "Prompt generated below. Clipboard permission was blocked.",
    promptGenerated: "Prompt generated below.",
    pasteModelJsonFirst: "Paste model JSON first."
  }
} satisfies Record<LanguageCode, Record<string, string>>;

export function createConsoleApi(baseUrl: string) {
  return {
    statusUrl(date: string): string {
      return `${baseUrl}/api/status?date=${encodeURIComponent(date)}`;
    },
    settledAnalysisUrl(date: string): string {
      return `${baseUrl}/api/analysis?date=${encodeURIComponent(date)}`;
    },
    previewUrl(): string {
      return `${baseUrl}/api/preview`;
    },
    manualPromptUrl(date: string): string {
      return `${baseUrl}/api/manual-analysis/prompt?date=${encodeURIComponent(date)}`;
    },
    manualPreviewUrl(): string {
      return `${baseUrl}/api/manual-analysis/preview`;
    },
    manualSettleUrl(): string {
      return `${baseUrl}/api/manual-analysis/settle`;
    },
    runtimeConfigUrl(): string {
      return `${baseUrl}/api/settings/runtime-config`;
    },
    equipmentUrl(): string {
      return `${baseUrl}/api/equipment`;
    },
    equipmentStateUrl(id: number): string {
      return `${baseUrl}/api/equipment/${encodeURIComponent(String(id))}/state`;
    },
    refreshPlan(mode: ConsoleMode, today: string, settledDate: string) {
      const statusUrl = this.statusUrl(today);

      if (mode === "preview") {
        return {
          mode,
          statusUrl,
          previewUrl: this.previewUrl()
        };
      }

      return {
        mode,
        statusUrl,
        settledAnalysisUrl: this.settledAnalysisUrl(settledDate)
      };
    }
  };
}

const api = createConsoleApi(serviceUrl);
let currentMode: ConsoleMode = "collection";
let consoleLanguage: LanguageCode = readStoredLanguage();
let runtimeSettingsDraft: {
  baseUrl: string;
  model: string;
  protocol: string;
  apiKey: string;
  extensionOrigins: string;
} | null = null;

function readStoredLanguage(): LanguageCode {
  if (typeof localStorage === "undefined") {
    return "zh";
  }

  return localStorage.getItem(LANGUAGE_STORAGE_KEY) === "en" ? "en" : "zh";
}

export function setConsoleLanguage(language: LanguageCode): void {
  consoleLanguage = language;

  if (typeof localStorage !== "undefined") {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }
}

function t(key: keyof typeof translations.en, replacements: Record<string, string> = {}): string {
  let value = translations[consoleLanguage][key];

  for (const [replacementKey, replacementValue] of Object.entries(replacements)) {
    value = value.replaceAll(`{${replacementKey}}`, replacementValue);
  }

  return value;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function fallbackThoughtSummary(analysis: DailyBattleAnalysis): string {
  const sections = [
    ...analysis.coreThemes,
    ...analysis.repeatedQuestions,
    ...analysis.newlyFormedJudgments,
    ...analysis.unclosedThinkingLoops,
    ...analysis.reusableMaterial,
    ...analysis.threadsToContinueTomorrow
  ].filter((item) => item.trim().length > 0);

  if (sections.length === 0) {
    return "今天还没有足够的捕获内容生成战况分析。AGE-FX 会继续等待 ChatGPT 和 Gemini 的对话记录，正式分析仍然在本地零点结算刚刚结束的昨天。";
  }

  return `今天的战况来自旧版结构化记录。主要线索是：${sections.join(" ")}\n\n这份兼容摘要不会回放原始聊天记录；新的结算和预览会直接生成更完整的长文战况分析。`;
}

function renderThoughtSummary(analysis: DailyBattleAnalysis): string {
  const summary = analysis.thoughtSummary?.trim() || fallbackThoughtSummary(analysis);
  const paragraphs = summary
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter((paragraph) => paragraph.length > 0);

  return `
    <section class="summary-panel" id="battle-analysis" aria-label="Daily battle summary">
      <p class="eyebrow">${escapeHtml(t("dailyBattleAnalysis"))}</p>
      <h2>${escapeHtml(analysis.thoughtTitle)}</h2>
      <div class="summary-copy">
        ${paragraphs.map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join("")}
      </div>
    </section>
  `;
}

function firstEquipment(
  recommendedEquipment: DailyBattleAnalysis["recommendedEquipment"]
): EquipmentRecommendation | null {
  return Array.isArray(recommendedEquipment)
    ? recommendedEquipment[0] ?? null
    : recommendedEquipment;
}

function mergeArchivedEquipment(
  analysis: DailyBattleAnalysis | null,
  items: EquipmentRecommendation[] = []
): EquipmentRecommendation | null {
  const recommendation = analysis ? firstEquipment(analysis.recommendedEquipment) : null;

  if (!recommendation) {
    return null;
  }

  const archivedItem = items.find(
    (item) =>
      item.analysisDate === analysis?.analysisDate &&
      item.equipmentName === recommendation.equipmentName &&
      item.equipmentType === recommendation.equipmentType
  );

  return {
    ...recommendation,
    ...archivedItem
  };
}

function renderSideRail(): string {
  return `
    <nav class="side-rail" aria-label="AGE-FX console navigation">
      <div class="side-orb" aria-hidden="true"></div>
      <button class="side-nav-button is-active" type="button" data-target="battle-analysis">${escapeHtml(t("navBattle"))}</button>
      <button class="side-nav-button" type="button" data-target="equipment-panel">${escapeHtml(t("navEquipment"))}</button>
      <button class="side-nav-button" type="button" data-target="runtime-settings">${escapeHtml(t("navApi"))}</button>
      <button class="side-nav-button" type="button" data-target="manual-bridge">${escapeHtml(t("navManualBridge"))}</button>
    </nav>
  `;
}

function renderEquipment(equipment: EquipmentRecommendation | null): string {
  if (!equipment) {
    return `
      <aside class="equipment-panel" id="equipment-panel">
        <p class="eyebrow">${escapeHtml(t("recommendedEquipment"))}</p>
        <h2>${escapeHtml(t("noEquipment"))}</h2>
        <p class="muted">${escapeHtml(t("formalEquipment"))}</p>
      </aside>
    `;
  }

  return `
    <aside class="equipment-panel" id="equipment-panel" aria-label="Recommended equipment">
      <div class="panel-heading">
        <p class="eyebrow">${escapeHtml(t("recommendedEquipment"))}</p>
        <span class="state-pill">${escapeHtml(equipment.state)}</span>
      </div>
      <h2>${escapeHtml(equipment.equipmentName)}</h2>
      <p class="equipment-why">${escapeHtml(equipment.whyThisEquipment)}</p>
      <dl>
        <dt>${escapeHtml(t("minimumVersion"))}</dt>
        <dd>${escapeHtml(equipment.minimumViableVersion)}</dd>
        <dt>${escapeHtml(t("expectedBenefit"))}</dt>
        <dd>${escapeHtml(equipment.expectedBenefit)}</dd>
        <dt>${escapeHtml(t("printPrompt"))}</dt>
        <dd>${escapeHtml(equipment.printPrompt)}</dd>
      </dl>
    </aside>
  `;
}

function renderPrintChamber(equipment: EquipmentRecommendation | null): string {
  if (!equipment) {
    return `
      <section class="print-chamber" aria-label="${escapeHtml(t("equipmentPrintChamber"))}">
        <p class="burst-status">${escapeHtml(t("fxBurstActive"))}</p>
        <p class="eyebrow">${escapeHtml(t("equipmentPrintChamber"))}</p>
        <h2>${escapeHtml(t("noPrintableEquipment"))}</h2>
        <p class="muted">${escapeHtml(t("noPrintableEquipmentCopy"))}</p>
      </section>
    `;
  }

  const canUpdateState = typeof equipment.id === "number";

  return `
    <section class="print-chamber" aria-label="${escapeHtml(t("equipmentPrintChamber"))}">
      <p class="burst-status">${escapeHtml(t("fxBurstActive"))}</p>
      <div class="print-chamber-grid">
        <div class="print-core">
          <p class="eyebrow">${escapeHtml(t("equipmentPrintChamber"))}</p>
          <h2>${escapeHtml(equipment.equipmentName)}</h2>
          <p class="equipment-why">${escapeHtml(equipment.whyThisEquipment)}</p>
          <div class="print-actions">
            ${
              canUpdateState
                ? `<button class="burst-toggle equipment-state-button" type="button" data-equipment-id="${escapeHtml(String(equipment.id))}" data-equipment-state="approved">${escapeHtml(t("confirmPrint"))}</button>
                   <button class="burst-toggle equipment-state-button secondary-action" type="button" data-equipment-id="${escapeHtml(String(equipment.id))}" data-equipment-state="archived">${escapeHtml(t("archiveEquipment"))}</button>`
                : `<span class="bridge-status">${escapeHtml(t("manualBridgePreviewCopy"))}</span>`
            }
            <span class="bridge-status" id="equipment-state-status"></span>
          </div>
        </div>
        <dl class="print-spec">
          <dt>${escapeHtml(t("equipmentType"))}</dt>
          <dd>${escapeHtml(equipment.equipmentType)}</dd>
          <dt>${escapeHtml(t("sourceBattleInsight"))}</dt>
          <dd>${escapeHtml(equipment.sourceBattleInsight)}</dd>
          <dt>${escapeHtml(t("minimumVersion"))}</dt>
          <dd>${escapeHtml(equipment.minimumViableVersion)}</dd>
          <dt>${escapeHtml(t("expectedBenefit"))}</dt>
          <dd>${escapeHtml(equipment.expectedBenefit)}</dd>
          <dt>${escapeHtml(t("printPrompt"))}</dt>
          <dd>${escapeHtml(equipment.printPrompt)}</dd>
        </dl>
      </div>
    </section>
  `;
}

function renderStatus(status: StatusResponse | null): string {
  if (!status) {
    return "";
  }

  const capturedMessagesLabel =
    status.capturedMessages === 1
      ? t("capturedMessage")
      : t("capturedMessages", { count: String(status.capturedMessages) });

  return `
    <div class="status-strip" aria-label="Service status">
      <span class="status-metric">
        <strong>${escapeHtml(t("data"))}</strong>
        ${escapeHtml(status.dataRoot)}
      </span>
      <span class="status-metric">
        <strong>${escapeHtml(t("capture"))}</strong>
        ${escapeHtml(capturedMessagesLabel)}
      </span>
    </div>
  `;
}

function renderLanguageSwitch(): string {
  return `
    <div class="language-switch" aria-label="${escapeHtml(t("language"))}">
      <span>${escapeHtml(t("language"))}</span>
      <button class="language-button" type="button" data-language="zh" aria-pressed="${consoleLanguage === "zh"}">${escapeHtml(t("chinese"))}</button>
      <button class="language-button" type="button" data-language="en" aria-pressed="${consoleLanguage === "en"}">${escapeHtml(t("english"))}</button>
    </div>
  `;
}

function renderTopbarActions(): string {
  return `
    <div class="topbar-tools-visible">
      <span class="capture-chip">${escapeHtml(t("cFunnelsCapture"))}: <strong>${escapeHtml(t("online"))}</strong></span>
      ${renderLanguageSwitch()}
      <button class="burst-toggle" id="burst-toggle" type="button" aria-pressed="false">
        ${escapeHtml(t("enterFxBurst"))}
      </button>
    </div>
  `;
}

export function renderRuntimeSettings(config: RuntimeConfig | null): string {
  const safeConfig = config ?? {
    baseUrl: "",
    model: "",
    hasApiKey: false,
    extensionOrigins: "",
    protocol: "responses"
  };
  const draft = readRuntimeSettingsDraft() ?? runtimeSettingsDraft;
  const values = draft
    ? {
        baseUrl: draft.baseUrl,
        model: draft.model,
        apiKey: draft.apiKey,
        extensionOrigins: draft.extensionOrigins,
        protocol: draft.protocol
      }
    : {
        baseUrl: safeConfig.baseUrl,
        model: safeConfig.model,
        apiKey: "",
        extensionOrigins: safeConfig.extensionOrigins,
        protocol: safeConfig.protocol
      };
  const protocol = values.protocol === "chat_completions" ? "chat_completions" : "responses";

  return `
    <section class="panel runtime-settings" id="runtime-settings" aria-label="${escapeHtml(t("apiSettings"))}">
      <h2>${escapeHtml(t("apiSettings"))}</h2>
      <p class="muted">${escapeHtml(t("apiSettingsCopy"))}</p>
      <div class="settings-grid">
        <label>
          <span>${escapeHtml(t("baseUrl"))}</span>
          <input id="runtime-base-url" type="url" value="${escapeHtml(values.baseUrl)}" autocomplete="off" />
        </label>
        <label>
          <span>${escapeHtml(t("model"))}</span>
          <input id="runtime-model" type="text" value="${escapeHtml(values.model)}" autocomplete="off" />
        </label>
        <label>
          <span>${escapeHtml(t("protocol"))}</span>
          <select id="runtime-protocol">
            <option value="responses"${protocol === "responses" ? " selected" : ""}>${escapeHtml(t("responsesApi"))}</option>
            <option value="chat_completions"${protocol === "chat_completions" ? " selected" : ""}>${escapeHtml(t("chatCompletionsCompatible"))}</option>
          </select>
        </label>
        <label>
          <span>${escapeHtml(t("apiKey"))}</span>
          <input id="runtime-api-key" type="password" value="${escapeHtml(values.apiKey)}" placeholder="${escapeHtml(t("apiKeyPlaceholder"))}" autocomplete="off" />
        </label>
        <label>
          <span>${escapeHtml(t("extensionOrigins"))}</span>
          <input id="runtime-extension-origins" type="text" value="${escapeHtml(values.extensionOrigins)}" autocomplete="off" />
        </label>
      </div>
      <div class="bridge-actions">
        <button class="burst-toggle" id="runtime-save-button" type="button">${escapeHtml(t("saveApiSettings"))}</button>
        <span class="bridge-status" id="runtime-settings-status">
          ${escapeHtml(safeConfig.hasApiKey ? t("apiKeyConfigured") : t("apiKeyMissing"))}
        </span>
      </div>
    </section>
  `;
}

function runtimeInputValue(id: string): string {
  return (document.getElementById(id) as HTMLInputElement | null)?.value.trim() ?? "";
}

function readRuntimeSettingsDraft(): typeof runtimeSettingsDraft {
  const baseUrlInput = document.querySelector<HTMLInputElement>("#runtime-base-url");

  if (!baseUrlInput) {
    return null;
  }

  return {
    baseUrl: runtimeInputValue("runtime-base-url"),
    model: runtimeInputValue("runtime-model"),
    protocol: runtimeInputValue("runtime-protocol"),
    apiKey: runtimeInputValue("runtime-api-key"),
    extensionOrigins: runtimeInputValue("runtime-extension-origins")
  };
}

function captureRuntimeSettingsDraft(): void {
  runtimeSettingsDraft = readRuntimeSettingsDraft();
}

function attachRuntimeSettingsHandlers(): void {
  document
    .querySelectorAll<HTMLInputElement | HTMLSelectElement>(
      "#runtime-base-url, #runtime-model, #runtime-protocol, #runtime-api-key, #runtime-extension-origins"
    )
    .forEach((input) => {
      input.addEventListener("input", captureRuntimeSettingsDraft);
      input.addEventListener("change", captureRuntimeSettingsDraft);
    });

  document.querySelector<HTMLButtonElement>("#runtime-save-button")?.addEventListener("click", () => {
    const status = document.querySelector<HTMLElement>("#runtime-settings-status");
    captureRuntimeSettingsDraft();

    fetch(api.runtimeConfigUrl(), {
      method: "PUT",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        baseUrl: runtimeInputValue("runtime-base-url"),
        model: runtimeInputValue("runtime-model"),
        protocol: runtimeInputValue("runtime-protocol"),
        apiKey: runtimeInputValue("runtime-api-key"),
        extensionOrigins: runtimeInputValue("runtime-extension-origins")
      })
    })
      .then(async (response) => {
        if (!response.ok) {
          throw new Error(await responseErrorMessage(response, "runtime config"));
        }

        return response.json() as Promise<RuntimeConfig>;
      })
      .then((config) => {
        runtimeSettingsDraft = {
          baseUrl: config.baseUrl,
          model: config.model,
          protocol: config.protocol,
          apiKey: "",
          extensionOrigins: config.extensionOrigins
        };
        if (status) {
          status.textContent = `${t("settingsSaved")} · ${
            config.hasApiKey ? t("apiKeyConfigured") : t("apiKeyMissing")
          }`;
        }
        const apiKeyInput = document.querySelector<HTMLInputElement>("#runtime-api-key");
        if (apiKeyInput) {
          apiKeyInput.value = "";
        }
      })
      .catch((error: unknown) => {
        if (status) {
          status.textContent = error instanceof Error ? error.message : String(error);
        }
      });
  });
}

function attachCommonHandlers(): void {
  document.querySelectorAll<HTMLButtonElement>(".language-button").forEach((button) => {
    button.addEventListener("click", () => {
      setConsoleLanguage(button.dataset.language === "en" ? "en" : "zh");
      refreshConsole().catch((error: unknown) => {
        renderError(error instanceof Error ? error.message : String(error));
      });
    });
  });

  const burstToggle = document.querySelector<HTMLButtonElement>("#burst-toggle");
  burstToggle?.addEventListener("click", () => {
    const burstActive = document.body.classList.toggle("burst");
    burstToggle.setAttribute("aria-pressed", String(burstActive));
    burstToggle.textContent = burstActive ? t("exitFxBurst") : t("enterFxBurst");
  });
}

function attachEquipmentStateHandlers(): void {
  document.querySelectorAll<HTMLButtonElement>(".equipment-state-button").forEach((button) => {
    button.addEventListener("click", () => {
      const id = Number(button.dataset.equipmentId);
      const state = button.dataset.equipmentState as EquipmentState | undefined;
      const status = document.querySelector<HTMLElement>("#equipment-state-status");

      if (!Number.isFinite(id) || !state) {
        return;
      }

      button.disabled = true;
      if (status) {
        status.textContent = "";
      }

      fetch(api.equipmentStateUrl(id), {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ state })
      })
        .then(async (response) => {
          if (!response.ok) {
            throw new Error(await responseErrorMessage(response, "equipment state"));
          }

          if (status) {
            status.textContent = t("equipmentStateUpdated");
          }

          return refreshConsole();
        })
        .catch((error: unknown) => {
          button.disabled = false;
          if (status) {
            const detail = error instanceof Error ? error.message : String(error);
            status.textContent = `${t("equipmentStateFailed")}: ${detail}`;
          }
        });
    });
  });
}

function attachSideRailHandlers(): void {
  const buttons = Array.from(document.querySelectorAll<HTMLButtonElement>(".side-nav-button"));

  buttons.forEach((button) => {
    button.addEventListener("click", () => {
      const targetId = button.dataset.target ?? "";
      const target = targetId ? document.getElementById(targetId) : null;

      buttons.forEach((item) => item.classList.toggle("is-active", item === button));

      if (!target) {
        return;
      }

      if (typeof target.scrollIntoView === "function") {
        target.scrollIntoView({
          behavior: "smooth",
          block: "start"
        });
      } else {
        window.location.hash = targetId;
      }
    });
  });
}

function renderRunNote(analysisDate: string, mode: "settled" | "preview" | "manual-preview"): string {
  if (mode === "settled") {
    return t("formalSettlementNote", { date: analysisDate });
  }

  if (mode === "manual-preview") {
    return t("manualPreviewNote", { date: analysisDate });
  }

  return t("temporaryPreviewNote", { date: analysisDate });
}

export function renderAnalysis(
  analysis: DailyBattleAnalysis,
  status: StatusResponse | null = null,
  mode: "settled" | "preview" | "manual-preview" = "settled"
): void {
  const app = document.querySelector<HTMLElement>("#app");

  if (!app) {
    return;
  }

  const equipment = firstEquipment(analysis.recommendedEquipment);

  app.innerHTML = `
    <header class="topbar">
      <div class="brand-block">
        ${renderTopbarActions()}
        <div class="brand-lockup" aria-label="AGE-FX Thought Console">
          <span class="brand-name">AGE<span>FX</span></span>
          <span class="brand-subtitle">Thought Console</span>
        </div>
        <p class="eyebrow">Daily Cognitive Sortie</p>
        <h1>${escapeHtml(analysis.thoughtTitle)}</h1>
        <p class="run-note">
          ${escapeHtml(renderRunNote(analysis.analysisDate, mode))}
        </p>
        ${renderStatus(status)}
      </div>
    </header>
    <div class="console-grid">
      ${renderSideRail()}
      ${renderPrintChamber(equipment)}
      <div class="analysis-stack" aria-label="Battle analysis">
        ${renderThoughtSummary(analysis)}
        ${
          mode === "preview"
            ? `<section class="panel">
                 <h2>${escapeHtml(t("livePreview"))}</h2>
                 <p class="muted">${escapeHtml(t("livePreviewCopy"))}</p>
                 <button class="burst-toggle" id="collection-button" type="button">${escapeHtml(t("back"))}</button>
               </section>`
            : mode === "manual-preview"
              ? `<section class="panel">
                   <h2>${escapeHtml(t("manualBridgePreview"))}</h2>
                   <p class="muted">${escapeHtml(t("manualBridgePreviewCopy"))}</p>
                   <button class="burst-toggle" id="collection-button" type="button">${escapeHtml(t("back"))}</button>
                 </section>`
              : ""
        }
      </div>
      ${renderEquipment(equipment)}
    </div>
  `;

  document.querySelector<HTMLButtonElement>("#collection-button")?.addEventListener("click", () => {
    currentMode = "collection";
    refreshConsole().catch((error: unknown) => {
      renderError(error instanceof Error ? error.message : String(error));
    });
  });
  attachEquipmentStateHandlers();
  attachSideRailHandlers();
  attachCommonHandlers();
}

export function renderCollectionStatus(
  today: string,
  settledDate: string,
  status: StatusResponse,
  settledAnalysis: DailyBattleAnalysis | null,
  runtimeConfig: RuntimeConfig | null = null,
  previewError: string | null = null,
  equipment: EquipmentRecommendation | null = settledAnalysis
    ? firstEquipment(settledAnalysis.recommendedEquipment)
    : null
): void {
  const app = document.querySelector<HTMLElement>("#app");

  if (!app) {
    return;
  }

  app.innerHTML = `
    <header class="topbar">
      <div class="brand-block">
        ${renderTopbarActions()}
        <div class="brand-lockup" aria-label="AGE-FX Thought Console">
          <span class="brand-name">AGE<span>FX</span></span>
          <span class="brand-subtitle">Thought Console</span>
        </div>
        <p class="eyebrow">Daily Cognitive Sortie</p>
        <h1>${settledAnalysis ? escapeHtml(settledAnalysis.thoughtTitle) : escapeHtml(t("collectingTitle"))}</h1>
        <p class="run-note">
          ${escapeHtml(t("collectionNote", { today, settledDate }))}
        </p>
        ${renderStatus(status)}
      </div>
    </header>
    <div class="console-grid">
      ${renderSideRail()}
      ${renderPrintChamber(equipment)}
      <div class="analysis-stack" aria-label="Battle analysis">
        ${
          settledAnalysis
            ? renderThoughtSummary(settledAnalysis)
            : `<section class="panel">
                 <h2>${escapeHtml(t("waitingForSettlement"))}</h2>
                 <p class="muted">${escapeHtml(t("noFormalAnalysis", { date: settledDate }))}</p>
               </section>`
        }
        <section class="panel">
          <h2>${escapeHtml(t("previewToday"))}</h2>
          <p class="muted">${escapeHtml(t("previewTodayCopy"))}</p>
          ${previewError ? `<p class="error-copy">${escapeHtml(previewError)}</p>` : ""}
          <p class="bridge-status" id="preview-status"></p>
          <button class="burst-toggle" id="preview-button" type="button">${escapeHtml(t("openPreview"))}</button>
        </section>
        ${renderRuntimeSettings(runtimeConfig)}
        ${renderManualBridge({
          date: today,
          title: t("manualModelBridge"),
          description: t("manualModelBridgeCopy"),
          allowSettle: false
        })}
        ${
          settledAnalysis
            ? ""
            : renderManualBridge({
                date: settledDate,
                title: t("manualSettlementBridge"),
                description: t("manualSettlementBridgeCopy"),
                allowSettle: true
              })
        }
      </div>
      ${renderEquipment(equipment)}
    </div>
  `;

  document.querySelector<HTMLButtonElement>("#preview-button")?.addEventListener("click", () => {
    const button = document.querySelector<HTMLButtonElement>("#preview-button");
    const statusElement = document.querySelector<HTMLElement>("#preview-status");

    currentMode = "preview";
    if (button) {
      button.disabled = true;
    }
    if (statusElement) {
      statusElement.textContent = t("previewStarting");
    }

    previewToday(today).catch((error: unknown) => {
      currentMode = "collection";
      renderCollectionStatus(
        today,
        settledDate,
        status,
        settledAnalysis,
        runtimeConfig,
        error instanceof Error ? error.message : String(error)
      );
    });
  });

  attachManualBridgeHandlers(status);
  attachRuntimeSettingsHandlers();
  attachEquipmentStateHandlers();
  attachSideRailHandlers();
  attachCommonHandlers();
}

function bridgeId(date: string, suffix: string): string {
  return `manual-${date}-${suffix}`;
}

function renderManualBridge(options: {
  date: string;
  title: string;
  description: string;
  allowSettle: boolean;
}): string {
  const promptId = bridgeId(options.date, "prompt-output");
  const inputId = bridgeId(options.date, "analysis-input");
  const statusId = bridgeId(options.date, "status");

  return `
    <section class="panel manual-bridge" id="manual-bridge" aria-label="${escapeHtml(options.title)}" data-manual-date="${escapeHtml(options.date)}">
      <h2>${escapeHtml(options.title)}</h2>
      <p class="muted">${escapeHtml(options.description)}</p>
      <div class="bridge-actions">
        <button class="burst-toggle manual-prompt-button" type="button" data-manual-date="${escapeHtml(options.date)}">${escapeHtml(t("copyPrompt"))}</button>
        <span class="bridge-status" id="${escapeHtml(statusId)}">${escapeHtml(t("readyForDate", { date: options.date }))}</span>
      </div>
      <textarea id="${escapeHtml(promptId)}" class="bridge-textarea manual-prompt-output" readonly aria-label="${escapeHtml(t("generatedPromptLabel"))}"></textarea>
      <textarea id="${escapeHtml(inputId)}" class="bridge-textarea manual-analysis-input" aria-label="${escapeHtml(t("pastedJsonLabel"))}" placeholder="${escapeHtml(t("pasteJsonPlaceholder"))}"></textarea>
      <div class="bridge-actions">
        <button class="burst-toggle manual-preview-button" type="button" data-manual-date="${escapeHtml(options.date)}">${escapeHtml(t("renderManualPreview"))}</button>
        ${
          options.allowSettle
            ? `<button class="burst-toggle manual-settle-button" type="button" data-manual-date="${escapeHtml(options.date)}">${escapeHtml(t("saveFormalSettlement"))}</button>`
            : ""
        }
      </div>
    </section>
  `;
}

function setManualBridgeStatus(date: string, message: string): void {
  const status = document.querySelector<HTMLElement>(`#${CSS.escape(bridgeId(date, "status"))}`);

  if (status) {
    status.textContent = message;
  }
}

async function copyManualPrompt(date: string): Promise<void> {
  const response = await fetch(api.manualPromptUrl(date));

  if (!response.ok) {
    throw new Error(await responseErrorMessage(response, "manual prompt"));
  }

  const payload = (await response.json()) as ManualPromptResponse;
  const output = document.querySelector<HTMLTextAreaElement>(
    `#${CSS.escape(bridgeId(date, "prompt-output"))}`
  );

  if (output) {
    output.value = payload.prompt;
  }

  if (navigator.clipboard) {
    try {
      await navigator.clipboard.writeText(payload.prompt);
      setManualBridgeStatus(date, t("promptCopied"));
      return;
    } catch {
      setManualBridgeStatus(date, t("promptGeneratedClipboardBlocked"));
      return;
    }
  }

  setManualBridgeStatus(date, t("promptGenerated"));
}

async function submitManualAnalysis(
  date: string,
  status: StatusResponse,
  mode: "preview" | "settle"
): Promise<void> {
  const input = document.querySelector<HTMLTextAreaElement>(
    `#${CSS.escape(bridgeId(date, "analysis-input"))}`
  );
  const analysisText = input?.value.trim() ?? "";

  if (!analysisText) {
    setManualBridgeStatus(date, t("pasteModelJsonFirst"));
    return;
  }

  const response = await fetch(
    mode === "preview" ? api.manualPreviewUrl() : api.manualSettleUrl(),
    {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ date, analysisText })
    }
  );

  if (!response.ok) {
    throw new Error(await responseErrorMessage(response, `manual ${mode}`));
  }

  const payload = (await response.json()) as AnalyzeResponse;

  if (!payload.analysis) {
    throw new Error("AGE-FX manual bridge response did not include analysis.");
  }

  if (mode === "settle") {
    currentMode = "collection";
    await refreshConsole();
    return;
  }

  renderAnalysis(payload.analysis, status, "manual-preview");
}

function attachManualBridgeHandlers(status: StatusResponse): void {
  document.querySelectorAll<HTMLButtonElement>(".manual-prompt-button").forEach((button) => {
    button.addEventListener("click", () => {
      const date = button.dataset.manualDate ?? "";

      copyManualPrompt(date).catch((error: unknown) => {
        setManualBridgeStatus(date, error instanceof Error ? error.message : String(error));
      });
    });
  });

  document.querySelectorAll<HTMLButtonElement>(".manual-preview-button").forEach((button) => {
    button.addEventListener("click", () => {
      const date = button.dataset.manualDate ?? "";

      submitManualAnalysis(date, status, "preview").catch((error: unknown) => {
        setManualBridgeStatus(date, error instanceof Error ? error.message : String(error));
      });
    });
  });

  document.querySelectorAll<HTMLButtonElement>(".manual-settle-button").forEach((button) => {
    button.addEventListener("click", () => {
      const date = button.dataset.manualDate ?? "";

      submitManualAnalysis(date, status, "settle").catch((error: unknown) => {
        setManualBridgeStatus(date, error instanceof Error ? error.message : String(error));
      });
    });
  });
}

export function todayIsoDate(date = new Date()): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

export function previousIsoDate(date = new Date()): string {
  const previousDay = new Date(date);
  previousDay.setDate(previousDay.getDate() - 1);

  return todayIsoDate(previousDay);
}

function renderError(message: string): void {
  const app = document.querySelector<HTMLElement>("#app");

  if (!app) {
    return;
  }

  app.innerHTML = `
    <section class="error-panel" role="alert">
      <p class="eyebrow">${escapeHtml(t("analysisFaultEyebrow"))}</p>
      <h1>${escapeHtml(t("analysisFaultTitle"))}</h1>
      <p>${escapeHtml(message)}</p>
    </section>
  `;
}

export async function responseErrorMessage(
  response: Response,
  label: string
): Promise<string> {
  let detail = "";

  try {
    const payload = (await response.clone().json()) as {
      message?: string;
      error?: string;
    };
    detail = payload.message ?? payload.error ?? "";
  } catch {
    detail = await response
      .clone()
      .text()
      .catch(() => "");
  }

  return detail
    ? `AGE-FX ${label} returned ${response.status}: ${detail}`
    : `AGE-FX ${label} returned ${response.status}`;
}

async function refreshConsole(): Promise<void> {
  const date = todayIsoDate();
  const settledDate = previousIsoDate();
  const plan = api.refreshPlan(currentMode, date, settledDate);
  const [statusResponse, runtimeConfigResponse] = await Promise.all([
    fetch(plan.statusUrl),
    fetch(api.runtimeConfigUrl())
  ]);

  if (!statusResponse.ok) {
    throw new Error(await responseErrorMessage(statusResponse, "status"));
  }

  const status = (await statusResponse.json()) as StatusResponse;
  const runtimeConfig = runtimeConfigResponse.ok
    ? ((await runtimeConfigResponse.json()) as RuntimeConfig)
    : null;

  if (plan.mode === "preview") {
    await renderPreview(date, status);
    return;
  }

  const settledAnalysisResponse = await fetch(plan.settledAnalysisUrl);
  let settledAnalysis: DailyBattleAnalysis | null = null;
  let settledEquipment: EquipmentRecommendation | null = null;

  if (settledAnalysisResponse.ok) {
    const payload = (await settledAnalysisResponse.json()) as AnalyzeResponse;
    settledAnalysis = payload.analysis ?? null;
    settledEquipment = settledAnalysis ? firstEquipment(settledAnalysis.recommendedEquipment) : null;
    const equipmentResponse = await fetch(api.equipmentUrl());

    if (equipmentResponse.ok) {
      const equipmentItems = ((await equipmentResponse.json()) as EquipmentListResponse).items;
      settledEquipment = mergeArchivedEquipment(settledAnalysis, equipmentItems);
    }
  } else if (settledAnalysisResponse.status !== 404) {
    throw new Error(await responseErrorMessage(settledAnalysisResponse, "analysis"));
  }

  renderCollectionStatus(
    date,
    settledDate,
    status,
    settledAnalysis,
    runtimeConfig,
    null,
    settledEquipment
  );
}

async function renderPreview(date: string, status: StatusResponse): Promise<void> {
  const response = await fetch(api.previewUrl(), {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ date })
  });

  if (!response.ok) {
    throw new Error(await responseErrorMessage(response, "preview"));
  }

  const payload = (await response.json()) as AnalyzeResponse;

  if (!payload.analysis) {
    throw new Error("AGE-FX preview response did not include analysis.");
  }

  renderAnalysis(payload.analysis, status, "preview");
}

async function previewToday(date: string): Promise<void> {
  const statusResponse = await fetch(api.statusUrl(date));

  if (!statusResponse.ok) {
    throw new Error(await responseErrorMessage(statusResponse, "status"));
  }

  await renderPreview(date, (await statusResponse.json()) as StatusResponse);
}

async function boot(): Promise<void> {
  await refreshConsole();
  window.setInterval(() => {
    refreshConsole().catch((error: unknown) => {
      renderError(error instanceof Error ? error.message : String(error));
    });
  }, REFRESH_INTERVAL_MS);
}

if (typeof window !== "undefined" && document.querySelector("#app")) {
  boot().catch((error: unknown) => {
    renderError(error instanceof Error ? error.message : String(error));
  });
}
